name: babylonjs_viewer
description: 3D Model Rendering with BabylonJS Viewer
version: 1.1.2
author: Burak Karahan
repository: https://github.com/MarlonJD/babylonjs_viewer
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/viewer/